import {
  Member,
  Family,
  DepartmentBudget,
  Expense,
  Vendor,
  Ministry,
  ServiceRoster,
  ChurchEvent,
  Facility,
  Asset,
  PastoralCareNote,
  PrayerRequest,
  ChurchProfile,
  SystemRole,
  RolePermissions,
  UserInvite,
  CoordinationGroup,
  GroupMessage,
  WorshipSong,
  WorshipPracticeGroup,
} from './types';

export const initialChurchProfile: ChurchProfile = {
  name: 'Grace Community Church',
  denomination: 'Nondenominational Evangelical',
  address: '450 Highland Avenue, Oakridge, CA 95608',
  phone: '(555) 234-8900',
  email: 'office@gracecommunityoak.org',
  leadPastor: 'Pastor David Robertson',
  website: 'www.gracecommunityoak.org',
  taxId: '94-3829104',
};

export const initialMembers: Member[] = [
  {
    id: 'm-1',
    firstName: 'David',
    lastName: 'Robertson',
    email: 'david.r@gracecommunityoak.org',
    phone: '(555) 234-8901',
    address: '102 Oak Ridge Lane, Oakridge, CA',
    role: 'Staff',
    status: 'Active',
    gender: 'Male',
    birthDate: '1975-04-12',
    baptismDate: '1990-06-15',
    familyId: 'fam-1',
    familyRole: 'Head',
    ministryGroups: ['Leadership Council', 'Pastoral Team'],
    joinedDate: '2015-08-01',
    notes: 'Lead Pastor. Preaching & vision.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'm-2',
    firstName: 'Sarah',
    lastName: 'Robertson',
    email: 'sarah.r@gracecommunityoak.org',
    phone: '(555) 234-8902',
    address: '102 Oak Ridge Lane, Oakridge, CA',
    role: 'Leader',
    status: 'Active',
    gender: 'Female',
    birthDate: '1978-09-21',
    baptismDate: '1992-05-10',
    familyId: 'fam-1',
    familyRole: 'Spouse',
    ministryGroups: ['Women\'s Ministry', 'Hospitality Team'],
    joinedDate: '2015-08-01',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'm-3',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'm.chen@techserve.com',
    phone: '(555) 345-1122',
    address: '88 Pinecrest St, Oakridge, CA',
    role: 'Leader',
    status: 'Active',
    gender: 'Male',
    birthDate: '1984-11-05',
    baptismDate: '2001-08-20',
    familyId: 'fam-2',
    familyRole: 'Head',
    ministryGroups: ['Worship Team', 'Media & AV'],
    joinedDate: '2018-03-15',
    notes: 'Sound engineer lead & acoustic guitar player.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'm-4',
    firstName: 'Emily',
    lastName: 'Chen',
    email: 'emily.chen@email.com',
    phone: '(555) 345-1123',
    address: '88 Pinecrest St, Oakridge, CA',
    role: 'Member',
    status: 'Active',
    gender: 'Female',
    birthDate: '1986-03-14',
    baptismDate: '2005-04-18',
    familyId: 'fam-2',
    familyRole: 'Spouse',
    ministryGroups: ['Sunday School', 'Children\'s Ministry'],
    joinedDate: '2018-03-15',
  },
  {
    id: 'm-5',
    firstName: 'Marcus',
    lastName: 'Vance',
    email: 'marcus.vance@youthfire.org',
    phone: '(555) 889-4421',
    address: '312 Willow Way, Oakridge, CA',
    role: 'Staff',
    status: 'Active',
    gender: 'Male',
    birthDate: '1991-07-30',
    baptismDate: '2006-07-12',
    familyId: 'fam-3',
    familyRole: 'Head',
    ministryGroups: ['Youth Ministry', 'Worship Team'],
    joinedDate: '2020-01-10',
    notes: 'Youth Pastor & Young Adults Coordinator.',
  },
  {
    id: 'm-6',
    firstName: 'Hannah',
    lastName: 'Miller',
    email: 'hannah.m@email.com',
    phone: '(555) 772-9011',
    address: '744 Sunset Blvd, Oakridge, CA',
    role: 'Leader',
    status: 'Active',
    gender: 'Female',
    birthDate: '1993-12-01',
    baptismDate: '2010-09-05',
    ministryGroups: ['Worship Team', 'Young Adults'],
    joinedDate: '2019-06-20',
    notes: 'Primary Worship Vocalist.',
  },
  {
    id: 'm-7',
    firstName: 'Robert',
    lastName: 'Taylor',
    email: 'rtaylor@oakridgebiz.com',
    phone: '(555) 441-2099',
    address: '15 Maple Dr, Oakridge, CA',
    role: 'Leader',
    status: 'Active',
    gender: 'Male',
    birthDate: '1962-02-18',
    baptismDate: '1978-04-16',
    familyId: 'fam-4',
    familyRole: 'Head',
    ministryGroups: ['Finance Committee', 'Facilities Team'],
    joinedDate: '2010-02-01',
    notes: 'Treasurer & Elder.',
  },
  {
    id: 'm-8',
    firstName: 'Grace',
    lastName: 'Taylor',
    email: 'gtaylor@email.com',
    phone: '(555) 441-2098',
    address: '15 Maple Dr, Oakridge, CA',
    role: 'Member',
    status: 'Active',
    gender: 'Female',
    birthDate: '1965-08-25',
    baptismDate: '1980-05-12',
    familyId: 'fam-4',
    familyRole: 'Spouse',
    ministryGroups: ['Hospitality Team', 'Prayer Team'],
    joinedDate: '2010-02-01',
  },
  {
    id: 'm-9',
    firstName: 'Joshua',
    lastName: 'Ames',
    email: 'joshua.a@email.com',
    phone: '(555) 601-3322',
    address: '502 Cedar Rd, Oakridge, CA',
    role: 'Regular Attender',
    status: 'Active',
    gender: 'Male',
    birthDate: '1998-05-19',
    ministryGroups: ['Welcome & Greeters'],
    joinedDate: '2023-11-12',
  },
  {
    id: 'm-10',
    firstName: 'Eleanor',
    lastName: 'Wright',
    email: 'ewright@seniorcare.org',
    phone: '(555) 902-1188',
    address: '12 Elderberry Ave, Oakridge, CA',
    role: 'Member',
    status: 'Active',
    gender: 'Female',
    birthDate: '1950-10-14',
    baptismDate: '1965-06-20',
    ministryGroups: ['Seniors Fellowship', 'Prayer Team'],
    joinedDate: '2012-04-05',
  }
];

export const initialFamilies: Family[] = [
  {
    id: 'fam-1',
    name: 'Robertson Family',
    primaryContactId: 'm-1',
    primaryContactName: 'David Robertson',
    address: '102 Oak Ridge Lane, Oakridge, CA',
    memberIds: ['m-1', 'm-2'],
  },
  {
    id: 'fam-2',
    name: 'Chen Family',
    primaryContactId: 'm-3',
    primaryContactName: 'Michael Chen',
    address: '88 Pinecrest St, Oakridge, CA',
    memberIds: ['m-3', 'm-4'],
  },
  {
    id: 'fam-4',
    name: 'Taylor Family',
    primaryContactId: 'm-7',
    primaryContactName: 'Robert Taylor',
    address: '15 Maple Dr, Oakridge, CA',
    memberIds: ['m-7', 'm-8'],
  }
];

export const initialDepartmentBudgets: DepartmentBudget[] = [
  {
    id: 'b-1',
    departmentName: 'Worship & Media',
    allocatedAmount: 18000,
    spentAmount: 12450,
    fiscalYear: '2026',
    code: 'DEPT-101',
    color: '#3b82f6',
  },
  {
    id: 'b-2',
    departmentName: 'Facilities & Operations',
    allocatedAmount: 45000,
    spentAmount: 32100,
    fiscalYear: '2026',
    code: 'DEPT-102',
    color: '#10b981',
  },
  {
    id: 'b-3',
    departmentName: 'Children & Youth Ministry',
    allocatedAmount: 15000,
    spentAmount: 9800,
    fiscalYear: '2026',
    code: 'DEPT-103',
    color: '#f59e0b',
  },
  {
    id: 'b-4',
    departmentName: 'Community Outreach & Missions',
    allocatedAmount: 22000,
    spentAmount: 16500,
    fiscalYear: '2026',
    code: 'DEPT-104',
    color: '#8b5cf6',
  },
  {
    id: 'b-5',
    departmentName: 'Church Administration & Software',
    allocatedAmount: 28000,
    spentAmount: 19400,
    fiscalYear: '2026',
    code: 'DEPT-105',
    color: '#ec4899',
  },
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp-1',
    title: 'Sanctuary Sound Board Cable Upgrade',
    department: 'Worship & Media',
    amount: 850.00,
    date: '2026-07-20',
    category: 'Equipment & Tech',
    vendor: 'ProAudio Direct',
    requestedBy: 'Michael Chen',
    status: 'Paid',
    receiptRef: 'INV-9021-PAD',
    notes: 'Replaced crackling XLR snakes and stage drop boxes.',
  },
  {
    id: 'exp-2',
    title: 'Church Property HVAC Quarterly Service',
    department: 'Facilities & Operations',
    amount: 1420.00,
    date: '2026-07-18',
    category: 'Maintenance & Repairs',
    vendor: 'Oakridge Climate Control',
    requestedBy: 'Robert Taylor',
    status: 'Paid',
    receiptRef: 'INV-44182',
    notes: 'Standard summer inspection & AC filter replacement in Main Hall.',
  },
  {
    id: 'exp-3',
    title: 'Summer Youth Camp Curriculum & Crafts',
    department: 'Children & Youth Ministry',
    amount: 680.50,
    date: '2026-07-15',
    category: 'Events & Supplies',
    vendor: 'Christian Book Distributors',
    requestedBy: 'Marcus Vance',
    status: 'Approved',
    receiptRef: 'REC-CBD-8812',
    notes: 'Workbooks and craft supplies for 45 youth participants.',
  },
  {
    id: 'exp-4',
    title: 'Monthly Church Electric & Gas Utility',
    department: 'Facilities & Operations',
    amount: 2150.00,
    date: '2026-07-10',
    category: 'Utilities & Facilities',
    vendor: 'City Power & Gas Co.',
    requestedBy: 'Robert Taylor',
    status: 'Paid',
    receiptRef: 'UTIL-0726',
  },
  {
    id: 'exp-5',
    title: 'Church Website & Cloud Management Renewal',
    department: 'Church Administration & Software',
    amount: 450.00,
    date: '2026-07-05',
    category: 'Software & Software',
    vendor: 'ChurchCentral Cloud Systems',
    requestedBy: 'David Robertson',
    status: 'Paid',
    receiptRef: 'CCC-ANNUAL-2026',
  },
  {
    id: 'exp-6',
    title: 'Community Food Pantry Support Grant',
    department: 'Community Outreach & Missions',
    amount: 1500.00,
    date: '2026-07-02',
    category: 'Missions Outflow',
    vendor: 'Oakridge Community Hope Center',
    requestedBy: 'Sarah Robertson',
    status: 'Paid',
    receiptRef: 'GRANT-2026-07',
  },
  {
    id: 'exp-7',
    title: 'Stage Lighting LED Bar Fixtures',
    department: 'Worship & Media',
    amount: 1200.00,
    date: '2026-07-25',
    category: 'Equipment & Tech',
    vendor: 'Sweetwater Sound',
    requestedBy: 'Michael Chen',
    status: 'Pending',
    notes: 'Replacing blown halogen pars with energy-efficient RGBW LED bars.',
  },
];

export const initialVendors: Vendor[] = [
  {
    id: 'v-1',
    name: 'ProAudio Direct',
    category: 'A/V & Stage Equipment',
    contactPerson: 'David Miller',
    phone: '(800) 555-0199',
    email: 'orders@proaudiodirect.com',
    accountDetails: 'Acct # 884-GCC',
  },
  {
    id: 'v-2',
    name: 'Oakridge Climate Control',
    category: 'HVAC & Plumbing',
    contactPerson: 'Frank Castle',
    phone: '(555) 890-3344',
    email: 'service@oakridgeclimate.com',
    accountDetails: 'Contract # AC-2024-GCC',
  },
  {
    id: 'v-3',
    name: 'City Power & Gas Co.',
    category: 'Utilities',
    contactPerson: 'Customer Service',
    phone: '(800) 441-9000',
    email: 'billing@citypowergas.gov',
    accountDetails: 'Acct # 992-1049-01',
  },
  {
    id: 'v-4',
    name: 'ChurchCentral Cloud Systems',
    category: 'Software & Hosting',
    contactPerson: 'Support Team',
    phone: '(888) 220-3000',
    email: 'billing@churchcentralcloud.com',
  },
];

export const initialMinistries: Ministry[] = [
  {
    id: 'min-1',
    name: 'Worship & Production Team',
    category: 'Worship',
    leaderId: 'm-3',
    leaderName: 'Michael Chen',
    description: 'Vocalists, musicians, sound technicians, and slide operators for weekly services.',
    memberCount: 14,
    meetingSchedule: 'Thursdays 7:00 PM (Rehearsal)',
  },
  {
    id: 'min-2',
    name: 'Youth & Student Ministry',
    category: 'Children & Youth',
    leaderId: 'm-5',
    leaderName: 'Marcus Vance',
    description: 'Middle and High school student discipleship, Friday night youth fellowship, and summer camps.',
    memberCount: 28,
    meetingSchedule: 'Fridays 6:30 PM',
  },
  {
    id: 'min-3',
    name: 'Hospitality & Greeters',
    category: 'Hospitality & Care',
    leaderId: 'm-2',
    leaderName: 'Sarah Robertson',
    description: 'First impressions team, ushers, morning coffee setup, and new visitor welcome desk.',
    memberCount: 18,
    meetingSchedule: 'Sundays 8:30 AM',
  },
  {
    id: 'min-4',
    name: 'Facilities & Maintenance Volunteers',
    category: 'Operations & Tech',
    leaderId: 'm-7',
    leaderName: 'Robert Taylor',
    description: 'Property upkeep, work days, setup/teardown for events, and facility repairs.',
    memberCount: 9,
    meetingSchedule: '1st Saturday of Month 9:00 AM',
  },
];

export const initialServiceRosters: ServiceRoster[] = [
  {
    id: 'rost-1',
    date: '2026-08-02',
    serviceType: 'Sunday Morning Service',
    notes: 'Communion Sunday. Need extra ushers.',
    roles: [
      { roleName: 'Preacher / Lead', assignedMemberId: 'm-1', assignedMemberName: 'David Robertson', status: 'Confirmed' },
      { roleName: 'Worship Leader', assignedMemberId: 'm-3', assignedMemberName: 'Michael Chen', status: 'Confirmed' },
      { roleName: 'Vocalist', assignedMemberId: 'm-6', assignedMemberName: 'Hannah Miller', status: 'Confirmed' },
      { roleName: 'Audio Engineer', assignedMemberId: 'm-3', assignedMemberName: 'Michael Chen', status: 'Confirmed' },
      { roleName: 'Lead Greeter', assignedMemberId: 'm-9', assignedMemberName: 'Joshua Ames', status: 'Confirmed' },
      { roleName: 'Nursery Lead', assignedMemberId: 'm-4', assignedMemberName: 'Emily Chen', status: 'Pending' },
    ],
  },
  {
    id: 'rost-2',
    date: '2026-08-09',
    serviceType: 'Sunday Morning Service',
    notes: 'Guest speaker panel.',
    roles: [
      { roleName: 'Preacher / Lead', assignedMemberId: 'm-1', assignedMemberName: 'David Robertson', status: 'Confirmed' },
      { roleName: 'Worship Leader', assignedMemberId: 'm-6', assignedMemberName: 'Hannah Miller', status: 'Confirmed' },
      { roleName: 'Audio Engineer', assignedMemberId: 'm-3', assignedMemberName: 'Michael Chen', status: 'Pending' },
      { roleName: 'Lead Greeter', assignedMemberId: 'm-2', assignedMemberName: 'Sarah Robertson', status: 'Confirmed' },
      { roleName: 'Nursery Lead', assignedMemberId: 'm-4', assignedMemberName: 'Emily Chen', status: 'Confirmed' },
    ],
  },
];

export const initialChurchEvents: ChurchEvent[] = [
  {
    id: 'evt-1',
    title: 'Sunday Worship & Word Service',
    category: 'Service',
    startDate: '2026-08-02T10:00',
    endDate: '2026-08-02T11:45',
    location: 'Main Sanctuary',
    organizer: 'David Robertson',
    status: 'Scheduled',
    expectedAttendance: 220,
    description: 'Weekly morning corporate worship service, sermon series in Colossians.',
  },
  {
    id: 'evt-2',
    title: 'Worship Team Midweek Rehearsal',
    category: 'Rehearsal',
    startDate: '2026-07-30T19:00',
    endDate: '2026-07-30T21:00',
    location: 'Main Sanctuary Stage',
    organizer: 'Michael Chen',
    status: 'Scheduled',
    expectedAttendance: 12,
  },
  {
    id: 'evt-3',
    title: 'Friday Night Youth Encounter',
    category: 'Small Group',
    startDate: '2026-07-31T18:30',
    endDate: '2026-07-31T21:00',
    location: 'Youth Lounge & Gym',
    organizer: 'Marcus Vance',
    status: 'Scheduled',
    expectedAttendance: 35,
    description: 'Games, pizza, student worship, and small group breakout sessions.',
  },
  {
    id: 'evt-4',
    title: 'Community Outreach Clean-up Day',
    category: 'Outreach',
    startDate: '2026-08-08T09:00',
    endDate: '2026-08-08T13:00',
    location: 'Oakridge Community Park',
    organizer: 'Sarah Robertson',
    status: 'Scheduled',
    expectedAttendance: 40,
    description: 'Park cleanup and barbecue for local neighborhood families.',
  },
];

export const initialFacilities: Facility[] = [
  {
    id: 'fac-1',
    name: 'Main Worship Sanctuary',
    capacity: 350,
    features: ['HD Projectors', '32-ch Audio Board', 'Stage Lighting', 'AC', 'Padded Seating'],
    status: 'Available',
  },
  {
    id: 'fac-2',
    name: 'Fellowship Hall & Kitchen',
    capacity: 180,
    features: ['Commercial Stove', 'Refrigerators', 'Round Tables & Chairs', 'A/V System'],
    status: 'Available',
  },
  {
    id: 'fac-3',
    name: 'Youth Room & Activity Hub',
    capacity: 75,
    features: ['Stage', 'Sound System', 'Gaming Consoles', 'Couches'],
    status: 'Booked',
  },
  {
    id: 'fac-4',
    name: 'Conference Room 201',
    capacity: 25,
    features: ['Conference Table', 'Smart TV / Zoom Setup', 'Whiteboard'],
    status: 'Available',
  },
];

export const initialAssets: Asset[] = [
  {
    id: 'ast-1',
    name: 'Behringer X32 Digital Mixing Console',
    category: 'Audio/Visual',
    serialNumber: 'BX32-2022-9011',
    purchaseDate: '2022-04-10',
    purchaseCost: 2800.00,
    location: 'Main Sanctuary Sound Booth',
    condition: 'Excellent',
    nextMaintenanceDate: '2026-10-15',
    notes: 'Firmware updated to v4.06.',
  },
  {
    id: 'ast-2',
    name: 'Epson PowerLite Pro HD Laser Projector',
    category: 'Audio/Visual',
    serialNumber: 'EP-9021-HD',
    purchaseDate: '2021-09-01',
    purchaseCost: 3400.00,
    location: 'Main Sanctuary Ceiling Mount',
    condition: 'Good',
    nextMaintenanceDate: '2026-09-01',
    notes: 'Filter cleaned quarterly.',
  },
  {
    id: 'ast-3',
    name: 'Yamaha C3 Grand Piano',
    category: 'Musical Instrument',
    serialNumber: 'YAM-C3-58190',
    purchaseDate: '2016-11-20',
    purchaseCost: 14500.00,
    location: 'Main Sanctuary Stage',
    condition: 'Good',
    nextMaintenanceDate: '2026-08-15',
    notes: 'Tuned 3x per year by Master Keys Service.',
  },
  {
    id: 'ast-4',
    name: 'Church Passenger Van (15-Seater Ford Transit)',
    category: 'Vehicle',
    serialNumber: '1FTBR1Y82MKA09112',
    purchaseDate: '2021-03-12',
    purchaseCost: 38500.00,
    location: 'Church Parking Lot Bay 1',
    condition: 'Good',
    nextMaintenanceDate: '2026-08-30',
    notes: 'Oil change and tire rotation scheduled for late August.',
  },
  {
    id: 'ast-5',
    name: 'Youth Room Soundcraft Mixer & Powered Speakers',
    category: 'Audio/Visual',
    serialNumber: 'SC-12-PA',
    purchaseDate: '2020-08-05',
    purchaseCost: 1800.00,
    location: 'Youth Lounge',
    condition: 'Needs Repair',
    nextMaintenanceDate: '2026-07-28',
    notes: 'Channel 3 input jack is intermittent. Cable repair required.',
  },
];

export const initialPastoralNotes: PastoralCareNote[] = [
  {
    id: 'past-1',
    memberId: 'm-10',
    memberName: 'Eleanor Wright',
    pastorName: 'David Robertson',
    date: '2026-07-22',
    type: 'Visitation',
    summary: 'Visited Eleanor at Oakridge Senior Living. She is recovering well from her knee surgery and asked for prayers for her grandson.',
    followUpDate: '2026-08-05',
    isConfidential: false,
  },
  {
    id: 'past-2',
    memberId: 'm-3',
    memberName: 'Michael Chen',
    pastorName: 'David Robertson',
    date: '2026-07-15',
    type: 'Discipleship',
    summary: 'Met for coffee to discuss leadership succession for the Media & Tech ministry. Michael recommended training two younger apprentices.',
    followUpDate: '2026-08-10',
    isConfidential: false,
  },
];

export const initialPrayerRequests: PrayerRequest[] = [
  {
    id: 'pr-1',
    title: 'Eleanor Wright - Knee Surgery Recovery',
    requestedBy: 'Eleanor Wright',
    memberId: 'm-10',
    dateAdded: '2026-07-18',
    category: 'Health',
    status: 'Active',
    notes: 'Pray for rapid healing and physical therapy strength.',
  },
  {
    id: 'pr-2',
    title: 'Youth Summer Camp Safety & Spiritual Breakthrough',
    requestedBy: 'Marcus Vance',
    memberId: 'm-5',
    dateAdded: '2026-07-10',
    category: 'Spiritual',
    status: 'Active',
    notes: '35 students registered. Pray for open hearts.',
  },
  {
    id: 'pr-3',
    title: 'Job Search Guidance for Mark Davis',
    requestedBy: 'Robert Taylor',
    dateAdded: '2026-06-25',
    category: 'Financial/Jobs',
    status: 'Answered',
    notes: 'Mark received a full-time position offer at Oakridge Tech!',
  },
];

export const defaultRolePermissions: Record<SystemRole, RolePermissions> = {
  'Administrator': {
    canManageMembers: true,
    canManageFinances: true,
    canManageRosters: true,
    canManageEvents: true,
    canManageAssets: true,
    canAccessPastoralCare: true,
    canManageGroups: true,
    canInviteUsers: true,
  },
  'Pastor / Minister': {
    canManageMembers: true,
    canManageFinances: false,
    canManageRosters: true,
    canManageEvents: true,
    canManageAssets: false,
    canAccessPastoralCare: true,
    canManageGroups: true,
    canInviteUsers: true,
  },
  'Treasurer / Finance': {
    canManageMembers: false,
    canManageFinances: true,
    canManageRosters: false,
    canManageEvents: false,
    canManageAssets: true,
    canAccessPastoralCare: false,
    canManageGroups: true,
    canInviteUsers: false,
  },
  'Department Leader': {
    canManageMembers: false,
    canManageFinances: false,
    canManageRosters: true,
    canManageEvents: true,
    canManageAssets: true,
    canAccessPastoralCare: false,
    canManageGroups: true,
    canInviteUsers: false,
  },
  'Member / Volunteer': {
    canManageMembers: false,
    canManageFinances: false,
    canManageRosters: false,
    canManageEvents: false,
    canManageAssets: false,
    canAccessPastoralCare: false,
    canManageGroups: true,
    canInviteUsers: false,
  },
};

export const initialUserInvites: UserInvite[] = [
  {
    id: 'inv-1',
    email: 'marcus.vance@youthfire.org',
    name: 'Marcus Vance',
    role: 'Department Leader',
    status: 'Accepted',
    invitedBy: 'David Robertson',
    dateSent: '2026-07-10',
    accessGroups: ['Youth Ministry Team', 'Worship Team'],
    inviteCode: 'GCC-YOUTH-8891',
    notes: 'Youth Pastor access',
  },
  {
    id: 'inv-2',
    email: 'rtaylor@oakridgebiz.com',
    name: 'Robert Taylor',
    role: 'Treasurer / Finance',
    status: 'Accepted',
    invitedBy: 'David Robertson',
    dateSent: '2026-07-01',
    accessGroups: ['Leadership Council', 'Finance Team'],
    inviteCode: 'GCC-FINANCE-2026',
    notes: 'Church Treasurer portal login',
  },
  {
    id: 'inv-3',
    email: 'm.chen@techserve.com',
    name: 'Michael Chen',
    role: 'Department Leader',
    status: 'Accepted',
    invitedBy: 'David Robertson',
    dateSent: '2026-07-05',
    accessGroups: ['Worship Team', 'A/V & Production Tech'],
    inviteCode: 'GCC-WORSHIP-3310',
  },
  {
    id: 'inv-4',
    email: 'clara.bennett@email.com',
    name: 'Clara Bennett',
    role: 'Member / Volunteer',
    status: 'Pending',
    invitedBy: 'David Robertson',
    dateSent: '2026-07-24',
    accessGroups: ['Hospitality & Greeters'],
    inviteCode: 'GCC-INV-9904',
    notes: 'New Sunday Greeter volunteer',
  },
  {
    id: 'inv-5',
    email: 'samuel.p@gracecommunityoak.org',
    name: 'Pastor Samuel Park',
    role: 'Pastor / Minister',
    status: 'Pending',
    invitedBy: 'David Robertson',
    dateSent: '2026-07-26',
    accessGroups: ['Leadership Council', 'Pastoral Care Team'],
    inviteCode: 'GCC-PASTOR-1042',
    notes: 'Associate Pastor joining next month',
  },
];

export const initialCoordinationGroups: CoordinationGroup[] = [
  {
    id: 'grp-1',
    name: 'Worship Team Coordination',
    category: 'Worship',
    description: 'Weekly chord sheets, song selections, rehearsal schedules, and stage arrangements.',
    avatarBg: 'bg-blue-600',
    memberIds: ['m-1', 'm-3', 'm-5', 'm-6'],
    isPrivate: false,
    createdBy: 'Michael Chen',
    createdDate: '2026-07-01',
    pinnedAnnouncement: '📢 Rehearsal this Thursday at 7:00 PM. Please review "Build My Life" in Key of E.',
  },
  {
    id: 'grp-2',
    name: 'Youth Ministry & Student Leaders',
    category: 'Youth',
    description: 'Friday night youth fellowship plans, summer camp logistics, and small group leaders.',
    avatarBg: 'bg-amber-500',
    memberIds: ['m-1', 'm-5'],
    isPrivate: false,
    createdBy: 'Marcus Vance',
    createdDate: '2026-07-05',
    pinnedAnnouncement: '🔥 Friday Night Encounter set for 6:30 PM in Youth Lounge. Pizza provided!',
  },
  {
    id: 'grp-3',
    name: 'Pastoral & Elders Council',
    category: 'Leadership',
    description: 'Confidential ministry strategy, pastoral visitations sync, and elder board updates.',
    avatarBg: 'bg-emerald-600',
    memberIds: ['m-1', 'm-2', 'm-7'],
    isPrivate: true,
    createdBy: 'David Robertson',
    createdDate: '2026-06-15',
    pinnedAnnouncement: '🔒 Monthly board meeting scheduled for Aug 4th at 6:00 PM.',
  },
  {
    id: 'grp-4',
    name: 'A/V, Sound & Media Crew',
    category: 'Facilities',
    description: 'Sound board setup, livestream routing, camera operating roster, and tech maintenance.',
    avatarBg: 'bg-indigo-600',
    memberIds: ['m-3', 'm-7'],
    isPrivate: false,
    createdBy: 'Michael Chen',
    createdDate: '2026-07-12',
  },
];

export const initialGroupMessages: GroupMessage[] = [
  {
    id: 'msg-1',
    groupId: 'grp-1',
    senderId: 'm-3',
    senderName: 'Michael Chen',
    senderRole: 'Worship Leader',
    text: 'Hey team! Here are the 4 songs for this Sunday August 2nd:\n1. Gratitude (Key of B)\n2. Build My Life (Key of E)\n3. Living Hope (Key of C)\n4. What A Beautiful Name (Key of D)',
    timestamp: 'Yesterday at 4:15 PM',
    isAnnouncement: true,
    attachmentName: 'Sunday_Aug2_Songpack.pdf',
    reactions: [
      { emoji: '🙌', count: 3, users: ['m-1', 'm-6', 'm-5'] },
      { emoji: '🎸', count: 2, users: ['m-5', 'm-6'] },
    ],
  },
  {
    id: 'msg-2',
    groupId: 'grp-1',
    senderId: 'm-6',
    senderName: 'Hannah Miller',
    senderRole: 'Vocalist',
    text: 'Sounds great Michael! I will take lead vocals on Living Hope.',
    timestamp: 'Yesterday at 4:32 PM',
  },
  {
    id: 'msg-3',
    groupId: 'grp-1',
    senderId: 'm-5',
    senderName: 'Marcus Vance',
    senderRole: 'Youth Pastor & Guitar',
    text: 'Got it. I will handle acoustic guitar and backup vocals for Build My Life. See everyone Thursday at 7 PM!',
    timestamp: 'Yesterday at 5:01 PM',
    reactions: [{ emoji: '👍', count: 2, users: ['m-3', 'm-1'] }],
  },
  {
    id: 'msg-4',
    groupId: 'grp-2',
    senderId: 'm-5',
    senderName: 'Marcus Vance',
    senderRole: 'Youth Pastor',
    text: 'Reminder: 35 students registered for the summer encounter night! Make sure small group materials are printed.',
    timestamp: 'Today at 9:00 AM',
    isAnnouncement: true,
  },
  {
    id: 'msg-5',
    groupId: 'grp-3',
    senderId: 'm-1',
    senderName: 'Pastor David Robertson',
    senderRole: 'Lead Pastor',
    text: 'Please remember in prayer the Wright family and our community outreach event coming up next week.',
    timestamp: 'Today at 10:15 AM',
    reactions: [{ emoji: '🙏', count: 3, users: ['m-2', 'm-7'] }],
  },
];

export const initialWorshipSongs: WorshipSong[] = [
  {
    id: 'song-1',
    title: 'Way Maker',
    artistAuthor: 'Sinach / Osinachi Kalu Okoro Egbu',
    defaultKey: 'G Major',
    bpm: 68,
    ccliNumber: '7115744',
    themeTags: ['Praise', 'Miracles', 'Faithfulness', 'Presence'],
    chordSheetUrl: 'https://praisecharts.com',
    audioLink: 'https://youtube.com',
    lyricsPreview: 'You are here, moving in our midst, I worship You, I worship You. Way maker, miracle worker, promise keeper...',
  },
  {
    id: 'song-2',
    title: 'Living Hope',
    artistAuthor: 'Phil Wickham & Brian Johnson',
    defaultKey: 'D Major',
    bpm: 72,
    ccliNumber: '7106807',
    themeTags: ['Resurrection', 'Salvation', 'Grace', 'Hope'],
    chordSheetUrl: 'https://praisecharts.com',
    audioLink: 'https://youtube.com',
    lyricsPreview: 'How great the chasm that lay between us, how high the mountain I could not climb...',
  },
  {
    id: 'song-3',
    title: 'Build My Life',
    artistAuthor: 'Housefires / Pat Barrett',
    defaultKey: 'E Major',
    bpm: 68,
    ccliNumber: '7070345',
    themeTags: ['Surrender', 'Foundation', 'Holiness', 'Devotion'],
    chordSheetUrl: 'https://praisecharts.com',
    audioLink: 'https://youtube.com',
    lyricsPreview: 'Worthy of every song we could ever sing, worthy of all the praise we could ever bring...',
  },
  {
    id: 'song-4',
    title: 'Goodness of God',
    artistAuthor: 'Bethel Music / Jenn Johnson',
    defaultKey: 'A Major',
    bpm: 70,
    ccliNumber: '7117726',
    themeTags: ['Gratitude', 'Faithfulness', 'Love', 'Testimony'],
    chordSheetUrl: 'https://praisecharts.com',
    audioLink: 'https://youtube.com',
    lyricsPreview: 'I love You, Lord, for Your mercy never fails me. All my days, I have been held in Your hands...',
  },
  {
    id: 'song-5',
    title: '10,000 Reasons (Bless The Lord)',
    artistAuthor: 'Matt Redman',
    defaultKey: 'G Major',
    bpm: 73,
    ccliNumber: '6016351',
    themeTags: ['Blessing', 'Morning', 'Eternity', 'Praise'],
    chordSheetUrl: 'https://praisecharts.com',
    audioLink: 'https://youtube.com',
    lyricsPreview: 'Bless the Lord O my soul, O my soul, worship His holy name. Sing like never before...',
  },
];

export const initialWorshipPracticeGroups: WorshipPracticeGroup[] = [
  {
    id: 'wpg-1',
    title: 'Sunday Morning Service Practice - Aug 2',
    serviceDate: '2026-08-02',
    practiceTime: 'Thursday 7:00 PM - 9:00 PM',
    leaderName: 'Michael Chen',
    assignedMemberIds: ['m-3', 'm-7', 'm-[Date]', 'm-5'],
    songIds: ['song-1', 'song-2', 'song-3'],
    notes: 'Focus on transitioning smoothly from Way Maker to Living Hope. Vocal soundcheck at 6:45 PM.',
    status: 'Upcoming',
  },
  {
    id: 'wpg-2',
    title: 'Youth Encounter Night Practice - Aug 7',
    serviceDate: '2026-08-07',
    practiceTime: 'Wednesday 6:30 PM',
    leaderName: 'Marcus Vance',
    assignedMemberIds: ['m-5', 'm-3'],
    songIds: ['song-3', 'song-4'],
    notes: 'Acoustic set arrangement. Acoustic guitar and cajon.',
    status: 'Upcoming',
  },
];

